name: github_actions

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node-ci:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    uses: cursorvers/cursor-macbookpro2019-workflows/.github/workflows/node-ci-reusable.yml@v1.1
    with:
      node-version: ${{ matrix.node-version }}
      working-directory: '.'
      run-lint: true
      run-test: true
      run-build: true
